### ISSUE TITLE
toggleAnimationClass('is-exiting') not working

### ISSUE THREAD

**Issue by pflores2704** [miguel-perez/smoothState.js#104]
Hi,

Well, I found out this smoothState.js thing today and it has been really helpful. But, I've been having some problems with the class that triggers the "alternate-reverse" animation in the CSS. I'm using Chrome 38.

Thanks in advance...

Here is the code:

The functions.js is the same from the example:

``` js
// Contents of functions.js
;(function($) {
  'use strict';
  var $body = $('html, body'),
      content = $('#main').smoothState({
        // Runs when a link has been activated
        onStart: {
          duration: 250, // Duration of our animation
          render: function (url, $container) {
            // toggleAnimationClass() is a public method
            // for restarting css animations with a class
            content.toggleAnimationClass('is-exiting');
            // Scroll user to the top
            $body.animate({
              scrollTop: 0
            });
          }
        }
      }).data('smoothState');
      //.data('smoothState') makes public methods available
})(jQuery);
```

This is the HTML:

``` html
    <fieldset id="main" class="scene">
            <div class="outer-wrapper scene_element scene_element--fadeInRight">
                <div class="gaussian-blur blur"></div>
                <div class="inner-wrapper text-center">
                    <form action="" method="POST" role="form">
                        <legend><h1 class="">AQUARIUM</h1></legend>
                        <div class="form-group">
                            <input type="email" 
                                   spellcheck="false" 
                                   class="form-control" 
                                   id="email" 
                                   placeholder="Correo">
                            <input type="password" 
                                   class="form-control" 
                                   id="password" 
                                   placeholder="Contrase&ntilde;a">
                        </div>
                        <button type="submit" class="btn btn-default">Iniciar Sesión</button>
                        <label id="account" for="">&iquest;No tienes cuenta?</label>
                        <a href="registro"><button type="button" class="btn btn-success">Regístrarse</button></a>
                    </form>
                </div>
            </div>
        </fieldset>
```

And this is the css:

``` css
.scene .scene_element {
  -webkit-animation-duration: 0.85s;
  -webkit-transition-timing-function: ease-in;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
}

.scene .scene_element--fadeInRight {
  -webkit-animation-name: fadeInRight;
}

.scene.is-exiting .scene_element {
  -webkit-animation-direction: alternate-reverse;
}

/*
 * Keyframes
 */
@-webkit-keyframes fadeInRight {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
  }

  100% {
    opacity: 1;
    -webkit-transform: none;
            transform: none;
  }
}
```

P.S: Apologize me for my basic english...
