### ISSUE TITLE
Foundation plugins and smoothState.js

### ISSUE THREAD

**Issue by phifa** [miguel-perez/smoothState.js#262]
Hi there, 
I am using the foundation framework and want to use smoothState.js. Does anybody know how to re-initialize foundation plugins with smoothstate.js? They only work if I hit browser refresh. All the other jQuery plugins seem to work - just foundation is giving me a headache... I think an example/demo would be really helpful, maybe the same for the other famous css framework Bootstrap? 

I tried this: 

**Adding Plugins After Page Load**
http://foundation.zurb.com/sites/docs/javascript.html#adding-plugins-after-page-load 

and this: 

**Adding Content to Plugins**
http://foundation.zurb.com/sites/docs/javascript.html#adding-content-to-plugins 

...without success. I guess I just don't really when to use onAfter and onReady? And then I was given the link by @miguel-perez but I also do not understand how to include that. 
https://gist.github.com/miguel-perez/476046a42d229251fec3 

thank you!

**Comment by baj226** [comment]
Hi there,

I'm also having trouble with smoothState and Foundation 6.

I've tried using the instructions here, but to no avail. The fixes I've found via Google haven't helped, either.

I think I need some very _basic_ help.

Below is what everything looks like, without any fixes applied.

app.js:

```
// @codekit-prepend "jquery.smoothState.min.js";

$(document).foundation();

$(function () {
    'use strict';
    var $page = $('#main'),
        options = {
            debug: true,
            prefetch: true,
            cacheLength: 2,
            onStart: {
                duration: 0, // Duration of our animation, was 250
                render: function ($container) {
                    // Add your CSS animation reversing class
                    $container.addClass('is-exiting');
                    // Restart your animation
                    smoothState.restartCSSAnimations();
                }
            },
            onReady: {
                duration: 0,
                render: function ($container, $newContent) {
                    // Remove your CSS animation reversing class
                    //            $container.removeClass('is-exiting');
                    // Inject the new content
                    $container.html($newContent);
                }
            },
            onAfter: function ($container) {
                $container.removeClass('is-exiting');
                console.log('after');
                $(document).foundation();
            },
        },
        smoothState = $page.smoothState(options).data('smoothState');
}); 
```

Before the closing body tag:

```
<script src="https://code.jquery.com/jquery-1.12.1.min.js" integrity="sha256-I1nTg78tSrZev3kjvfdM5A5Ak/blglGzlaZANLPDl3I=" crossorigin="anonymous"></script>
<script src="foundation.min.js"></script>
<script src="app-min.js"></script>
```

Any help is appreciated. Thanks!

**Comment by phifa** [comment]
I even submitted a premium request and heard nothing so far. If you are interested in premium support: 
http://foundation.zurb.com/support/premium-support.html

@baj226 maybe we need to open a ticket here https://github.com/zurb/foundation-sites/issues. I created an entry to the forum but have not heard back: 
http://foundation.zurb.com/forum/posts/39007-foundation-and-smoothstatejs

**Comment by phifa** [comment]
@baj226 maybe we need to open a ticket here https://github.com/zurb/foundation-sites/issues. I created an entry to the forum but have not heard back: 
http://foundation.zurb.com/forum/posts/39007-foundation-and-smoothstatejs

**Comment by phifa** [comment]
This is how I tried it, but without success. 

```

// Init on document ready
$(document).ready(function(){
    pageInit();
});

// Init with Ajax
$(function(){
    'use strict';
    var $page = $('#ajaxwrap'),
        options = {
            debug: true,
            prefetch: true,
            blacklist: '.noAjax',
            cacheLength: 2,
            onStart: {
                duration: 200, // Duration of our animation
                render: function ($container) {
                    // Add your CSS animation reversing class
                    $container.addClass('is-exiting');
                    // Restart your animation
                    smoothState.restartCSSAnimations();
                }
            },
            onReady: {
                duration: 0,
                render: function ($container, $newContent) {
                    // Remove your CSS animation reversing class
                    $container.removeClass('is-exiting');
                    // Inject the new content
                    $container.html($newContent);
                    pageInit();
                }
            },
            onAfter: function($container, $newContent) {
                // Maybe something here??
            }
        },
        smoothState = $page.smoothState(options).data('smoothState');
});

// All JS in this function
function pageInit(){

    // Init Foundation Elements
    $(document).foundation();

    // Other init stuff, all works 
   // ...

}


```

**Comment by CHEWX** [comment]
I'm having no troubles with both F5 and F6. 

Could you re-create in a Fiddle.

**Comment by phifa** [comment]
Hey @CHEWX, could you post you app.js? A Fiddle does not work as I need multiple pages, but I have put an example on a server, here: http://p352632.mittwaldserver.info/index.html 

As you can see, on opening, the sticky menu on the right works normally. Now go to the second page, animated with smoothstate. Great. There the accordion works great too. But when you go to page1 again, sticky does not stick. Only Browser reload makes it work.

**Comment by CHEWX** [comment]
@phifa 

What JavaScript paths are you compiling from Foundation.

**Comment by phifa** [comment]
@chewx This is my config.yml. It is just the standard sass based template with all plugins integrated: 

```
# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "bower_components/foundation-sites/js/foundation.abide.js"
    - "bower_components/foundation-sites/js/foundation.accordion.js"
    - "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    - "bower_components/foundation-sites/js/foundation.drilldown.js"
    - "bower_components/foundation-sites/js/foundation.dropdown.js"
    - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/js/foundation.equalizer.js"
    - "bower_components/foundation-sites/js/foundation.interchange.js"
    - "bower_components/foundation-sites/js/foundation.magellan.js"
    - "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.orbit.js"
    - "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    - "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/js/foundation.reveal.js"
    - "bower_components/foundation-sites/js/foundation.slider.js"
    - "bower_components/foundation-sites/js/foundation.sticky.js"
    - "bower_components/foundation-sites/js/foundation.tabs.js"
    - "bower_components/foundation-sites/js/foundation.toggler.js"
    - "bower_components/foundation-sites/js/foundation.tooltip.js"
    - "bower_components/smoothstate/src/jquery.smoothState.js"
    # Paths to your own project code are here
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js" 

```
