### ISSUE TITLE
is-exiting not working

### ISSUE THREAD

**Issue by beersy001** [miguel-perez/smoothState.js#41]
The reversal of the animation does not work for me. In FireFox, it will work if I click the same link again, whilst the initial animation is loading. Here's my code:
SCSS:

``` css
.is-exiting {
    .scene__element {
        animation-direction: alternate-reverse;
        -webkit-animation-direction: alternate-reverse;
    }
}
```

smoothState:

``` javascript
window.onload = function() {
    pageScripts();

    var $body = $('html, body'); // Define jQuery collection 
    var content = $('#main').smoothState({
        prefetch: true,
        development: true,
        onStart : {
            duration: 1000,
            render: function (url, $container) {
                content.toggleAnimationClass('is-exiting');
                console.log("rendering");
                $body.animate({ 'scrollTop': 0 });
            }
        },
        onEnd : {
            duration: 0, // Duration of the animations, if any.
            render: function (url, $container, $content) {
                $body.css('cursor', 'auto');
                $body.find('a').css('cursor', 'auto');
                $container.html($content);
                pageScripts();
            }
        }
    }).data('smoothState');
};
```
